spring.application.name=demo
server.port=8082

# ── H2 (comentados para no quitarlos) ──
# spring.datasource.url=jdbc:h2:mem:proyectosdb
# spring.datasource.username=cadiabet
# spring.datasource.password=admin123
# spring.datasource.driver-class-name=org.h2.Driver
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ── PostgreSQL ──
spring.datasource.url=jdbc:postgresql://localhost:5433/proyectosdb
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect